### ISSUE TITLE
Enable scale item column in rqt sub-window

### ISSUE THREAD

**Issue by jacknlliu** [ros-visualization/rqt#125]
Every rqt plugin like `topic monitor`, we can't scale the item column width, this lead that we can't see every detail easily.

![rqt_topic](https://user-images.githubusercontent.com/6220143/32412333-124a4376-c22f-11e7-9c3a-e667d1f2594a.png)

**Comment by dirk-thomas** [comment]
Each rqt plugin is providing the UI on its own. Therefore `rqt` can't do anything about it. Please consider filling issues in the issue tracker of each plugin which has this problem (e.g. https://github.com/ros-visualization/rqt_topic). It will likely speed up the fix if you could provide a pull request for these plugins.

Since there is nothing which can be done in this repository I will close the ticket. Please feel free to comment and e.g. add references to other tickets you are creating for future readers.
