### ISSUE TITLE
Failed to load nodelet

### ISSUE THREAD

**Issue by hecperleo** [ros-visualization/rqt#129]
Hi, I can not find my error. Last week I was using without problems my plugin, but now I get this output if I run rqt and click on Plugins->myplugin: 

`[ERROR] [1522672973.392465626]: Failed to load nodelet [rqt_mygui/MyPlugin_1] of type [rqt_mygui/MyPlugin]: Could not find library corresponding to plugin rqt_mygui/MyPlugin. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.`

If I run rqt --force-discover I get exactly the same error. 

At package.xml I am exporting like this: 

```
  <export>
    <rqt_gui plugin="${prefix}/plugin.xml"/>
  </export>
```

And my plugin.xml: 

```
<library path="lib/librqt_mygui">
  <class name="rqt_mygui/MyPlugin" type="rqt_mygui::MyPlugin" base_class_type="rqt_gui_cpp::Plugin">
    <description>
      C++ GUI plugin.
    </description>
    <qtgui>
      <label>C++ Plugin</label>
      <icon type="theme">system-help</icon>
      <statustip>UI</statustip>
    </qtgui>
  </class>
</library>
```

If I run rqt --list-plugins I get this correct output: 

```
rqt --list-plugins
rqt_action.action_plugin.ActionPlugin
rqt_bag.bag.Bag
rqt_console.console.Console
rqt_dep.ros_pack_graph.RosPackGraph
rqt_graph.ros_graph.RosGraph
rqt_image_view/ImageView
rqt_launch.launch_plugin.LaunchPlugin
rqt_logger_level.logger_level.LoggerLevel
rqt_moveit.moveit_plugin.MoveitPlugin
rqt_msg.messages.Messages
rqt_mygui/MyPlugin
rqt_nav_view.nav_view_plugin.NavViewPlugin
rqt_plot.plot.Plot
rqt_pose_view.pose_view.PoseView
rqt_publisher.publisher.Publisher
rqt_py_console.py_console.PyConsole
rqt_reconfigure.param_plugin.ParamPlugin
rqt_robot_monitor.robot_monitor_plugin.RobotMonitorPlugin
rqt_robot_steering.robot_steering.RobotSteering
rqt_runtime_monitor.runtime_monitor.RuntimeMonitor
rqt_rviz/RViz
rqt_service_caller.service_caller.ServiceCaller
rqt_shell.shell.Shell
rqt_srv.services.Services
rqt_tf_tree.tf_tree.RosTfTree
rqt_top.top_plugin.Top
rqt_topic.topic.Topic
rqt_web.web.Web
```

I also tried to remove ~/.config/ros.org/rqt_gui.ini and run rqt or rqt --force-discover after that without success.

Any idea? Thank you.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
