### ISSUE TITLE
rqt_smach: Smach Viewer needs to be migrated from rx

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#15]
The rx Smach Viewer at: http://www.ros.org/wiki/smach_viewer

Should be migrated to the rqt framework as soon as time allows

**Comment by dirk-thomas** [comment]
@ablasdel: we should delegate this to the maintainer of the current stack.

**Comment by ablasdel** [comment]
Ok I'll do that. 

The current maintainer is listed as follows in the stack.xml: @wmeeusse
<author>Maintained by Wim Meeussen</author>

**Comment by dirk-thomas** [comment]
The chance that Wim will migrate that is pretty low. Then we should either ask @jbohren as the original author or have to ask the community who will take maintainership.

**Comment by jbohren** [comment]
I don't have time to migrate it at the moment, and I won't have time for at least a few months. It shouldn't be too hard for someone who's familiar with QT in python to migrate it, though, and it should be pretty similar to the migration of rxgraph to QT since @kwc had forked SMACH viewer to make the more recent rxgraph.

**Comment by jbohren** [comment]
Has there been any motion on this? I might have some spare cycles coming up that I can put into it.

**Comment by ablasdel** [comment]
At this moment nobody here has time to work on it.
If you have some time to port it over that would be most helpful.

**Comment by 130s** [comment]
Closing this ticket, since it looks like development is going on in [another repo](https://github.com/ros-visualization/executive_smach_visualization).
