### ISSUE TITLE
rqt source fragmentation

### ISSUE THREAD

**Issue by windelbouwman** [ros-visualization/rqt#201]
I searched through the rqt sourcecode, and the code is pretty fragmented across packages. This is my opinion, but I would suggest to re-organize the sourcecode into less packages which are somewhat larger.

This has the following benefits:
- less packaging script overhead
- code is easier to navigate
- less configuration management
- Easy change in multiple software components (which were before in seperate repositories)

Other benefits can be found here: https://danluu.com/monorepo/

**Comment by dirk-thomas** [comment]
The separation of the source code across multiple packages and a repositories is intentional:

* [python_qt_binding](https://github.com/ros-visualization/python_qt_binding) contains the Python binding abstraction which enables to use `rqt` with `PyQt` as well as `PySide`
* [qt_gui_core](https://github.com/ros-visualization/qt_gui_core) contains the ROS agnostic parts of the GUI as well as a ROS agnostic plugin framework
* `rqt` (this repo) contains the ROS specific parts of the GUI and plugin system
* `rqt_*` contains specific rqt plugins providing individual functionality, since each comes with its own dependencies and are maintained and released by different people they are commonly also separated

As your referenced page also mentions:

> Of course, there are downsides to using a monorepo. ... My point isn't that you should definitely switch to a monorepo; it's merely that using a monorepo isn't totally unreasonable
