### ISSUE TITLE
ValueError: PyCapsule_GetPointer called with incorrect name

### ISSUE THREAD

**Issue by rjcortese** [ros-visualization/rqt#212]
<img width="1757" alt="Screen Shot 2019-12-18 at 2 00 14 PM" src="https://user-images.githubusercontent.com/2792758/71122847-bac14880-219e-11ea-8b7d-2e9645c967f6.png">

Hello,
Has anyone seen this error before?
I'm running macOS 10.15.2 and followed the install and environment setup instructions from https://index.ros.org/doc/ros2/Installation/Eloquent/OSX-Install-Binary/
Any thoughts on how to fix this?
Thanks

**Comment by dirk-thomas** [comment]
Please do not post pictures of error messages. They are not text-searchable. Copy-n-paste the error message instead as plain text.

Do you have the exact same versions of Python, Qt, etc. installed? if they are different from the versions used by the computer which built the archive it could fail like this. You might want to try a from source build instead.

---

Also I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
