### ISSUE TITLE
Intensity scaling options image_view

### ISSUE THREAD

**Issue by jonbinney** [ros-visualization/rqt#63]
Right now in image_view, the scaling for depth images is automaticaly determined. It seems to take the smallest depth and make that white, make the largest depth black, and linearly scale in between. This can cause the depth image to flicker when single large or small depth values appear. Two options would be nice:

-option for the user to manually specify minimum and maximum
-a median filter on the min and max values for the scaling, so that even when the user does not manually specify min and max values, the image flickers less

**Comment by dirk-thomas** [comment]
Option to manually specify maximum is already implemented since 2ecf759cad6be04019c6f83574b22e9af8bb58d2 (minimum is implicitly set to 0). This should be enough to let the user choose between dynamic range detection (with best histogram usage but flickering) or specifying known interval.

If you would like to add more functionality please provide a pull request.
