### ISSUE TITLE
Warning "Could not import "pyside" bindings of qt_gui_cpp library" when opening rqt_gui with pyside

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#7]
By doing:

```
rosrun rqt_gui rqt_gui --qt-binding=pyside
```

I see:

```
    Could not import "pyside" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
    File "/u/isaito/link/rqt_dev/git/qt_gui_core/qt_gui_cpp/src/qt_gui_cpp/cpp_binding_helper.py", line 43, in <module>
    import libqt_gui_cpp_shiboken
    ImportError: No module named libqt_gui_cpp_shiboken
```

python_qt_binding is git pulled on 11/8/2012 3pm.

**Comment by DorianScholz** [comment]
This issue is due to a bug in PySide and it's binding generator shiboken since version 1.1.0: 
https://bugreports.qt-project.org/browse/PYSIDE-76

Some more information about this can be seen here:
https://code.ros.org/trac/ros-pkg/ticket/5450

I still have this problem, when compiling with PySide 1.1.2.

I assigned Dirk to this issue, as he has worked more on this.

**Comment by DorianScholz** [comment]
As this can only be fixed in PySide, please vote on their bug tracker to fix this issue using the aforementioned link.

**Comment by dirk-thomas** [comment]
work around in ros-visualization/qt_gui_core@9846d262d3eb4718c49b1641a680bfba449d375f

**Comment by sromberg** [comment]
I still have that issue. Did I miss something?

```
mapper@mapper-VirtualBox:/tmp$ source /opt/ros/indigo/setup.bash 
mapper@mapper-VirtualBox:/tmp$ rosrun rqt_gui rqt_gui --clear-config --qt-binding=pyside
Could not import "pyside" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui_cpp/cpp_binding_helper.py", line 39, in <module>
    import libqt_gui_cpp_shiboken
ImportError: No module named libqt_gui_cpp_shiboken
```

Versions:

```
mapper@mapper-VirtualBox:/tmp$ dpkg -l | grep pyside
...
ii  python-pyside                                         1.2.1-4build1                                             all          Python 
ii  ros-indigo-python-qt-binding                          0.2.14-0trusty-20141230-0031-+0000                        amd64
...
mapper@mapper-VirtualBox:/tmp$ dpkg -l | grep qt-gui
ii  cmake-qt-gui                                          2.8.12.2-0ubuntu3                                         amd64        Qt4 based user interface for CMake (cmake-gui)
ii  ros-indigo-qt-gui                                     0.2.26-0trusty-20141230-0050-+0000                        amd64        qt_gui provides the infrastructure for an integrated graphical user interface based on Qt. It is extensible with Python- and C++-based plugins (implemented in separate packages) which can contribute arbitrary widgets. It requires either PyQt or PySide bindings.
...
ii  ros-indigo-rqt-gui-py                                 0.2.14-1trusty-20141230-0443-+0000                        amd64        rqt_gui_py enables GUI plugins to use the Python client library for ROS.
```

**Comment by dirk-thomas** [comment]
The current binaries built on Trusty do not support PySide since the shipped `shiboken` version has a bug which prevents it from working: https://github.com/ros-visualization/qt_gui_core/blob/efc7692eab423a1cb7447c27f4e200d2216db2a4/qt_gui_cpp/src/qt_gui_cpp_shiboken/CMakeLists.txt#L44-L46

Until upstream fixes the problem there is nothing we can do about it.

**Comment by sromberg** [comment]
Ok, thanks for your explanation.

**Comment by acbuynak** [comment]
I am having this issue as well and have been unable to resolve it. I am not getting a segmentation fault and have been able to duplicate the issue on a different computer with the same setup. 

Setup:
  Ubuntu Bionic 18.04.4 LTS
  ROS1 Melodic / ROS2 Dashing
  ...Used [ROS Industrial Shell Script ](https://github.com/ros-industrial/industrial_training/blob/melodic/gh_pages/_downloads/ros-industrial-training-setup.sh)to Install + var fixes. 

**Q: Is this issue inherent to the Ubuntu Bionic binaries with the broken shiboken version as well?**
 I have been unable to determine if this bug was resolved upstream by PySide or if this is an error of my own actions.
Thanks!

**Error**
```
$ rosrun rqt_graph rqt_graph
PluginManager._discover() using cached plugin discovery information
Could not import "pyside" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui_cpp/cpp_binding_helper.py", line 39, in <module>
    from . import libqt_gui_cpp_shiboken
ImportError: cannot import name libqt_gui_cpp_shiboken
```



**Versions**
...
ii  python-pyside                                      1.2.2+source1-3
ii  ros-melodic-python-qt-binding             0.3.6-2bionic.20191210.224309  
...
ii  ros-melodic-rqt-gui                                0.5.0-0bionic.20191210.230329   
ii  ros-dashing-rqt-gui-py                           1.0.5-1bionic.20191212.195003

**Comment by aboutmei** [comment]
ubuntu18.04
conda 环境 python2.7 
ros melodic
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui_cpp/cpp_binding_helper.py", line 39, in <module>
    from . import libqt_gui_cpp_shiboken
ImportError: cannot import name libqt_gui_cpp_shiboken
实在不知道怎么解决了
